<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="685" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:21 PST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="685" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:21 PST">
      <class name="mavendemo.extent_report1">
        <test-method status="PASS" signature="startReport()[pri:0, instance:mavendemo.extent_report1@a7e666]" name="startReport" is-config="true" duration-ms="188" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:20 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="demoReportPass()[pri:0, instance:mavendemo.extent_report1@a7e666]" name="demoReportPass" duration-ms="10" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:20 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportPass -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:mavendemo.extent_report1@a7e666]" name="getResult" is-config="true" duration-ms="5" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:20 PST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportPass status=SUCCESS method=extent_report1.demoReportPass()[pri:0, instance:mavendemo.extent_report1@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="demoReportfail()[pri:0, instance:mavendemo.extent_report1@a7e666]" name="demoReportfail" duration-ms="2" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:20 PST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at mavendemo.extent_report1.demoReportfail(extent_report1.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportfail -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:mavendemo.extent_report1@a7e666]" name="getResult" is-config="true" duration-ms="2" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:20 PST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportfail status=FAILURE method=extent_report1.demoReportfail()[pri:0, instance:mavendemo.extent_report1@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:mavendemo.extent_report1@a7e666]" name="endReport" is-config="true" duration-ms="437" started-at="2020-01-29T10:41:20 PST" finished-at="2020-01-29T10:41:21 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- mavendemo.extent_report1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
